package uk.org.metadata.datagen

class SharedDatasets {

    static List<DataItem> PersonStatedGender = null
    static List<DataEnum> PersonPhenotypicSex = null
    static List<DataEnum> PersonKarytypicSex = null
    static List<DataEnum> Ethnicity = null
    static List<DataEnum> ChoiceYesNo = null
    static List<DataEnum> ChoiceYesNoNR = null
    static List<DataEnum> ChoiceYesNoUK = null
    static List<DataEnum> ConsentForm = null
    static List<DataEnum> ParticipantType = null
    static List<DataEnum> Consanguinity = null
    static List<DataEnum> BiologicalRelationship = null
    static List<DataEnum> GroupType = null
    static List<DataEnum> SpecificDisease = null
    static List<DataEnum> GMCSampleType = null
    static List<DataEnum> TumourType = null
    static List<DataEnum> ExcisionMargin = null
    static List<DataEnum> TissueSource = null
    static List<DataEnum> TypeOfFixative = null
    static List<DataEnum> ProcessingSchedule = null
    static List<DataEnum> DNAExtractionProtocol = null
    static List<DataEnum> ProlongedSampleStorage = null
    static List<DataEnum> TumourSampleType = null
    static List<DataEnum> DiseaseType = null
    static List<DataEnum> DiseaseSubType = null
    static List<DataEnum> ChoiceTrueFalse = null


//    static List<DataEnum> TypeOfFixative = null
//    static List<DataEnum> TypeOfFixative = null
//    static List<DataEnum> TypeOfFixative = null
//    static List<DataEnum> TypeOfFixative = null
//    static List<DataEnum> TypeOfFixative = null



    SharedDatasets(){
        setupData()
    }

    static void setupData(){


        DiseaseSubType = new ArrayList<DataEnum>()
        DiseaseSubType.add(new DataEnum("adult_glioma","Adult Glioma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","(ALL) Acute lymphoblastic leukaemia"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","(AML) Acute myeloid Leukaemia"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Chronic lymphocytic leukaemia "))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Acinar cell carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Acral lentiginous"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Adamantinoma of bone"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Adenocarcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Adenoid cystic carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Alveolar soft part sarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Anaplastic astrocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Anaplastic ependymoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Anaplastic ganglioglioma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Anaplastic oligodendroglioma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Anaplastic oligoastroc"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Angiomatoid fibrous histiocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Angiosarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Anorectal mucosal melanoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Atypical teratoid rhabdoid tumours"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Betel nut-induced oral cancer"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Biliary adenocarcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Biliary adenosquamous carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Biliary squamous cell carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Burkitt lymphoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Cancer not confirmed (pathology indeterminate)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Pathology indeterminate – cancer NOS (non-carcinoma, lymphoma , sarcoma etc)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Pathology indeterminate – carcinoma  NOS (Not otherwise specified)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Carcinosarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Central neurocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Childhood other"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Cholangiocarcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Chordoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Choriocarcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Chromophobe"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Chronic myeloid leukaemia"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Classical seminoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Clear cell"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Clear cell adenocarcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","CNS primitive neuroectodermal tumors"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Collecting duct"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Combined HCC-cholangiocarcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Conjunctival melanoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Conventional chondrosarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Dedifferentiated chondrosarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Dedifferentiated liposarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Dermal sarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Desmoplastic melanoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Desmoplastic round cell sarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Diffuse astrocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Diffuse large B-cell lymphoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Ductal"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Dysgerminomas"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Embryonal carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Embryonal tumour with multilayered rosettes"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Endodermal sinus"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Endometrioid adenocarcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Ependymoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Epithelioid angiosar"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Extracranial rhabdoid tumour"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Extraskeletal chondrosarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Extraskeletal chordoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia"," Extraventricular neurocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Fibrillary astrocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Fibrolamellar HCC"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Ganglioglioma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Gastric adenocarcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Gastric carcinoma with lymphoid stroma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Gemistocytic astrocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Genital mucosal melanoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Germ cell tumour"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Germinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Giant cell glioblastoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Glioblastoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Gliomatosis cerebri"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Gliosarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Gnathic bone"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Granulosa cell tumour"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Granulosa theca"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Haematological malignancy unclassified"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","HCC acinar"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","HCC compact"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","HCC trabecular"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Hepatocellular carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Hepatoid adenocarcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","High grade endometrial stromal sarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","High grade lymphoma NOS"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","High grade serous carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","HPV negative oropharyngeal cancer"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","HPV positive oropharyngeal cancer"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Intimal sarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Inverted papilloma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","IPMN with invasive carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Large cell"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Leiomyosarcoma from all sites"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Lentigo maligna"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Leydig cell tumour"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Lobular"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Low grade endometrial stromal sarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Low grade fibromyxoid sarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Low grade serous adenocarcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Lymphoepithelioma-like HCC"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Malignant peripheral nerve sheath tumour"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Malignant rhabdoid tumour"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","MCN with invasive carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Mediastinal B-cell lymphoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Medullary"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Medulloblastoma (CLA)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Medulloblastoma (DN)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Medulloblastoma (LCA)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Medulloblastoma (MBEN)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Medulloblastoma (medullomyoblastoma)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Medulloblastoma (melanotic)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Medulloblastoma (NOS)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Melanoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Mesenchymal"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Mesothelioma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Mixed germ cell tumour"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Mixed tumour type"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Mucinous carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","ultiple myeloma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Myelodysplastic syndrome (high risk)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","yoepithelioma / Malignant myoepithelioma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Myxofibrosarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Myxoid liposarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Myxoinflammatory fibroblastic sarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Myxopapillary ependymoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Nasopharyngeal carcinoma Type I"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Nasopharyngeal carcinoma Type II"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Nasopharyngeal carcinoma Type III"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Neuroblastoma (INPC)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Neuroblastoma (NOS)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Neuroendocrine"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Neuroendocrine carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Nodular"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Non specified renal carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Not available"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Oligoastrocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Oligodendroglioma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Oncocytic"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Orbital"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Oromucosal melanoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Ossifying fibromyxoid tumour"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Other"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Paediatric malignant glioma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Pancreatic adenocarcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Pancreatic adenosquamous carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Pancreatic neuroendocrine carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Papillary"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Papillary tumour of the pineal region"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Papillary Type 1"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Papillary Type 2"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Pilocytic astrocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Pilomyxoid astrocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Pineal tumour of intermediate differentiation"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Pineoblastoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Pineocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Pleomorphic sarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Pleomorphic xanthoastrocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Primary CNS"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Primary conventional osteosarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Primitive neuroectodermal tumour"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Protoplasmic astrocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","seudomyogenic haemangioemdothelioma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Rare sarcoma entities"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Rhabdomyosarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Sarcoma NOS"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Sarcomatoid carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Sarcomatoid HCC"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Schirrous HCC"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Sclerosing epithelioid fibrosarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Serous carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","erous cystadenocarcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Sertoli cell tumour"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Sertoli-Leydig"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Small cell"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Small cell carcinoma (including hypercalcaemic type)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Spermatocytic Seminoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Spitz"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","quamous cell"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Stromal tumour"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Subependymal giant cell astrocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Subependymoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Superficial spreading"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Synovial sarcoma - monophasic and biphasic"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Teratoma (immature)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Teratoma (mature)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Teratoma differentiated"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Teratoma undifferentiated"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","teratoma with malignant transformation"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Transitional cell carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Tubular / cribform"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Undifferentiated carcinoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Undifferentiated HCC"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Undifferentiated uterine sarcoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Unknown"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Urothelial (in situ)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Urothelial (invasive)"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Uveal melanoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Yolk sac tumour"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Non-Hodgkins B cell lymphoma low / moderate grade"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Classical Hodgkins"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Nodular Lymphocyte Predominant Hodgkins"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","T-cell lymphoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Myleoproliferative neoplasms"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Acute leukaemia other"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Follicular"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Medullary"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Anaplastic"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Adrenocortical"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Phaeochromocytoma"))
        DiseaseSubType.add(new DataEnum("acute lymphoblastic leukaemia","Paraganglioma"))
        DiseaseSubType.add(new DataEnum("parathyroid Carcinoma","Parathyroid Carcinoma"))
        DiseaseSubType.add(new DataEnum("pituitary carcinoma","Pituitary carcinoma"))

        DiseaseType = new ArrayList<DataEnum>()
        DiseaseType.add(new DataEnum("adult_glioma","Adult Glioma"))
        DiseaseType.add(new DataEnum("bladder","Bladder"))
        DiseaseType.add(new DataEnum("breast","Breast"))
        DiseaseType.add(new DataEnum("carcinoma_of_unknown_primary","Carcinoma of Unknown Primary"))
        DiseaseType.add(new DataEnum("childhood","Childhood"))
        DiseaseType.add(new DataEnum("colorectal","Colorectal"))
        DiseaseType.add(new DataEnum("endometrial_carcinoma","Endometrial Carcinoma"))
        DiseaseType.add(new DataEnum("haemonc","Haematology Oncology"))
        DiseaseType.add(new DataEnum("hepatopancreatobiliary","Hepatopancreatobiliary"))
        DiseaseType.add(new DataEnum("lung","Lung"))
        DiseaseType.add(new DataEnum("malignant_melanoma","Malignant Melanoma"))
        DiseaseType.add(new DataEnum("nasopharyngeal","Nasopharyngeal"))
        DiseaseType.add(new DataEnum("oral_oropharyngeal","Oral or Oropharyngeal"))
        DiseaseType.add(new DataEnum("ovarian","Ovarian"))
        DiseaseType.add(new DataEnum("prostate","Prostate"))
        DiseaseType.add(new DataEnum("renal","Renal"))
        DiseaseType.add(new DataEnum("sarcoma","Sarcoma"))
        DiseaseType.add(new DataEnum("sinonasal","Sinonasal"))
        DiseaseType.add(new DataEnum("testicular_germ_cell_tumours","Testicular Germ Cell Tumours"))
        DiseaseType.add(new DataEnum("upper_gastrointestinal","Upper Gastrointestinal"))
        DiseaseType.add(new DataEnum("unknown","Unknown"))
        DiseaseType.add(new DataEnum("endocrine","Endocrine"))
        DiseaseType.add(new DataEnum("other","Other"))


        TumourSampleType  = new ArrayList<DataEnum>()
        TumourSampleType.add(new DataEnum("sections","section"))
        TumourSampleType.add(new DataEnum("cores","cores"))
        TumourSampleType.add(new DataEnum("scrolls","scrolls"))
        TumourSampleType.add(new DataEnum("blocks","blocks"))

        ProlongedSampleStorage = new ArrayList<DataEnum>()
        ProlongedSampleStorage.add(new DataEnum("refrigeration","refrigeration (2-8 C)"))
        ProlongedSampleStorage.add(new DataEnum("vac_pack","vacuum pack at room temperature"))
        ProlongedSampleStorage.add(new DataEnum("refrigeration_and_vac_pack","refrigeration (2-8 C) and vacuum pack"))
        ProlongedSampleStorage.add(new DataEnum("room_temp","room temperature"))

        DNAExtractionProtocol = new ArrayList<DataEnum>()
        DNAExtractionProtocol.add(new DataEnum("covaris","GEL Covaris 65 (FFPE)"))
        DNAExtractionProtocol.add(new DataEnum("qiagen_80","GEL Qiagen 80 (FFPE)"))
        DNAExtractionProtocol.add(new DataEnum("qiagen_90","GEL Qiagen 90 (FFPE)"))
        DNAExtractionProtocol.add(new DataEnum("fresh_frozen","Fresh Frozen"))
        DNAExtractionProtocol.add(new DataEnum("cell_pellet_extraction","Cell Pellet Extraction"))


        ProcessingSchedule = new ArrayList<DataEnum>()
        ProcessingSchedule.add(new DataEnum("overnight","Overnight (routine)"))
        ProcessingSchedule.add(new DataEnum("urgent","Rapid run"))
        ProcessingSchedule.add(new DataEnum("extended","Extended (>48hrs)"))
        ProcessingSchedule.add(new DataEnum("extra_large_program","Extra Large Program (prostate only)"))

        TypeOfFixative = new ArrayList<DataEnum>()
        TypeOfFixative.add(new DataEnum("formal_saline","Formal saline"))
        TypeOfFixative.add(new DataEnum("neutral_buffered_formalin","Neutral buffered Formalin"))
        TypeOfFixative.add(new DataEnum("umfix","UMFix"))
        TypeOfFixative.add(new DataEnum("paxgene","Paxgene"))
        TypeOfFixative.add(new DataEnum("other","Other"))

        TissueSource = new ArrayList<DataEnum>()
        TissueSource.add(new DataEnum("bma_tumour_sorted_cells","Bone marrow aspirate tumour sorted cells"))
        TissueSource.add(new DataEnum("ct_guided_biopsy","CT-guided biopsy"))
        TissueSource.add(new DataEnum("endoscopic_biopsy","Endoscopic biopsy"))
        TissueSource.add(new DataEnum("endoscopic_ultrasound_guided_biopsy","Endoscopic ultrasound guided biopsy"))
        TissueSource.add(new DataEnum("endoscopic_ultrasound_guided_fna","Endoscopic ultrasound guided fine needle aspirate"))
        TissueSource.add(new DataEnum("laparoscopic_biopsy","Laparoscopic biopsy"))
        TissueSource.add(new DataEnum("laparoscopic_excision","Laparoscopic excision"))
        TissueSource.add(new DataEnum("mri_guided_biopsy","MRI-guided biopsy"))
        TissueSource.add(new DataEnum("non_guided_biopsy","Non-guided biopsy"))
        TissueSource.add(new DataEnum("surgical_resection","Surgical resection"))
        TissueSource.add(new DataEnum("stereotactically_guided_biopsy","Stereotactically guided biopsy"))
        TissueSource.add(new DataEnum("uss_guided_biopsy","USS-guided biopsy"))
        TissueSource.add(new DataEnum("non_standard_biopsy","Non-Standard Biopsy"))

        ExcisionMargin = new ArrayList()
        ExcisionMargin.add(new DataEnum("01","Excision margins are clear (distance from margin not stated)"))
        ExcisionMargin.add(new DataEnum("02","Excision margins are clear (tumour >5mm from the margin)"))
        ExcisionMargin.add(new DataEnum("03","Excision margins are clear (tumour >1mm but less than or equal to 5mm from the margin"))
        ExcisionMargin.add(new DataEnum("04","Tumour is less than or equal to 1mm from excision margin, but does not reach margin"))
        ExcisionMargin.add(new DataEnum("05","Tumour reaches excision margin"))
        ExcisionMargin.add(new DataEnum("06","Uncertain"))
        ExcisionMargin.add(new DataEnum("07","Margin not involved =>1mm"))
        ExcisionMargin.add(new DataEnum("08","Margin not involved <1mm"))
        ExcisionMargin.add(new DataEnum("09","Margin not involved 1-5mm"))
        ExcisionMargin.add(new DataEnum("98","Not applicable"))
        ExcisionMargin.add(new DataEnum("99","Not Known"))

        TumourType = new ArrayList()
        TumourType.add(new DataEnum("primary","Primary; source of cancer tumour sample"))
        TumourType.add(new DataEnum("recurrence_of_primary_tumour","Recurrence - a tumour has returned at the site of the original cancer after treatment"))
        TumourType.add(new DataEnum("metastatic_recurrence","Metastatic (different cancer site) which developed and was sampled after presentation and after treatment"))
        TumourType.add(new DataEnum("metastases","Metastatic (different cancer site) which was present and sampled at diagnosis before treatment"))

        GMCSampleType = new ArrayList()
        GMCSampleType.add(new DataEnum("additional_tumour_material","Additional Tumour material for research (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("blood_rna_gtc","Blood RNA stored in GTC buffer (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("bone_marrow_rna_gtc","Bone Marrow RNA stored in GTC buffer (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("buffy_coat","Buffy Coats (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("dna_blood_germline","DNA Blood Germline (CONSTITUTIONAL DNA)"))
        GMCSampleType.add(new DataEnum("dna_saliva	","DNA Saliva (CONSTITUTIONAL DNA)"))
        GMCSampleType.add(new DataEnum("dna_fibroblast","DNA Fibroblast (CONSITUTIONAL DNA)"))
        GMCSampleType.add(new DataEnum("dna_ff_germline","DNA FF Germline (CONSTITUTIONAL DNA) - non tumour tissue"))
        GMCSampleType.add(new DataEnum("dna_ffpe_tumour","DNA FFPE Tumour (TUMOUR DNA)"))
        GMCSampleType.add(new DataEnum("dna_ff_tumour","DNA FF Tumour (TUMOUR DNA)"))
        GMCSampleType.add(new DataEnum("dna_blood_tumour","DNA Blood from blood in Haematological malignancy Tumour (TUMOUR DNA)"))
        GMCSampleType.add(new DataEnum("dna_bone_marrow_aspirate_tumour_sorted_cells","DNA CD128 Tumour Sorted Cells (TUMOUR DNA) (Haem Onc samples)"))
        GMCSampleType.add(new DataEnum("dna_bone_marrow_aspirate_tumour_cells","DNA Bone Marrow Aspirate Tumour Cells (TUMOUR DNA) (Haem Onc samples)"))
        GMCSampleType.add(new DataEnum("edta_plasma","EDTA Plasma - Plasma for ctDNA (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("lysate_ffpe","Lysate FFPE (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("lysate_ff","Lysate Fresh Frozen (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("lysed_tumour_cells","Deparaffinised Lysed Tumour Cells in RNA-stabilised buffer (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("lihep_plasma","LiHep Plasma (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("rna_blood","RNA Blood (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("tumour_tissue_ffpe","Tumour Tissue FFPE (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("tumour_tissue_ff","Tumour Tissue Fresh Frozen (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("tumour_scrapings","FFPE Tumour scrapings or slides (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("serum","Serum (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("streck_plasma","Streck Plasma (OMICS SAMPLES)"))
        GMCSampleType.add(new DataEnum("dna_other_germline","DNA Other Germline"))
        GMCSampleType.add(new DataEnum("dna_fna_tumour","DNA FNA Tumour"))
        GMCSampleType.add(new DataEnum("dna_fluid_tumour","DNA Fluid Tumour"))
        GMCSampleType.add(new DataEnum("dna_other_tumour","DNA Other Tumour"))
        GMCSampleType.add(new DataEnum("foetal_dna_ff_germline","Foetal DNA Fresh Frozen Germline"))
        GMCSampleType.add(new DataEnum("foetal_dna_blood","Foetal DNA Blood"))

        PersonStatedGender = new ArrayList()
        PersonStatedGender.add(new DataEnum("2","Female"))
        PersonStatedGender.add(new DataEnum("1","Male"))
        PersonStatedGender.add(new DataEnum("9","Indeterminate"))
        PersonStatedGender.add(new DataEnum("X","Not Known (PERSON STATED GENDER CODE not recorded)"))

        PersonPhenotypicSex = new ArrayList()
        PersonPhenotypicSex.add(new DataEnum("2","Female"))
        PersonPhenotypicSex.add(new DataEnum("1","Male"))
        PersonPhenotypicSex.add(new DataEnum("9","Indeterminate"))

        PersonKarytypicSex = new ArrayList()
        PersonKarytypicSex.add(new DataEnum("XY", "XY"))
        PersonKarytypicSex.add(new DataEnum("XX","XX"))
        PersonKarytypicSex.add(new DataEnum("XO","XO"))
        PersonKarytypicSex.add(new DataEnum("XXY","XXY"))
        PersonKarytypicSex.add(new DataEnum("XYY","XYY"))
        PersonKarytypicSex.add(new DataEnum("XXX","XXX"))
        PersonKarytypicSex.add(new DataEnum("XXYY","XXYY"))
        PersonKarytypicSex.add(new DataEnum("XXXY","XXXY"))
        PersonKarytypicSex.add(new DataEnum("other","other"))
        PersonKarytypicSex.add(new DataEnum("unknown","unknown"))

        Ethnicity = new ArrayList()
        Ethnicity.add(new DataEnum("D","Mixed: White and Black Caribbean" ))
        Ethnicity.add(new DataEnum("E","Mixed: White and Black African"))
        Ethnicity.add(new DataEnum("F","Mixed: White and Asian"))
        Ethnicity.add(new DataEnum("G","Mixed: Any other mixed background"))
        Ethnicity.add(new DataEnum("A","White: British "))
        Ethnicity.add(new DataEnum("B","White: Irish"))
        Ethnicity.add(new DataEnum("C","White: Any other White background"))
        Ethnicity.add(new DataEnum("L","Asian or Asian British: Any other Asian background"))
        Ethnicity.add(new DataEnum("M","Black or Black British: Caribbean"))
        Ethnicity.add(new DataEnum("N",	"Black or Black British: African"))
        Ethnicity.add(new DataEnum("H",	"Asian or Asian British: Indian"))
        Ethnicity.add(new DataEnum("J",	"Asian or Asian British: Pakistani"))
        Ethnicity.add(new DataEnum("K",	"Asian or Asian British: Bangladeshi"))
        Ethnicity.add(new DataEnum("P",	"Black or Black British: Any other Black background"))
        Ethnicity.add(new DataEnum("S",	"Other Ethnic Groups: Any other ethnic group"))
        Ethnicity.add(new DataEnum("R",	"Other Ethnic Groups: Chinese"))
        Ethnicity.add(new DataEnum("Z",	"Not stated"))

        ChoiceYesNo = new ArrayList()
        ChoiceYesNo.add(new DataEnum("yes","Yes"))
        ChoiceYesNo.add(new DataEnum("no","No"))

        ChoiceTrueFalse = new ArrayList()
        ChoiceTrueFalse.add(new DataEnum("true","True"))
        ChoiceTrueFalse.add(new DataEnum("false","False"))

        ChoiceYesNoNR = new ArrayList()
        ChoiceYesNoNR.add(new DataEnum("yes","Yes"))
        ChoiceYesNoNR.add(new DataEnum("no","No"))
        ChoiceYesNoNR.add(new DataEnum("not relevant","not relevant"))

        ChoiceYesNoUK = new ArrayList()
        ChoiceYesNoUK.add(new DataEnum("yes","Yes"))
        ChoiceYesNoUK.add(new DataEnum("no","No"))
        ChoiceYesNoUK.add(new DataEnum("unknown","Unknown"))

        ConsentForm = new ArrayList()
        ConsentForm.add(new DataEnum("R1/R2(CF)"," R1/R2 Proband adult with rare disease (or for their adult relatives joining the Project) version 2.2 and date 24/09/2015"))
        ConsentForm.add(new DataEnum("R5(CF)","	R5 Parents of child aged under 16 (versioned for rare diseases) version 2.1 and date 24/09/2015"))
        ConsentForm.add(new DataEnum("R6(CF)","	R6 Parents of a (deceased) child aged under 16, baby or fetus (versioned for rare disease) version 2.1 and date 24/09/2015"))
        ConsentForm.add(new DataEnum("R7(CF)","	R7 Personal Consultees of an adult with a rare genetic disease to advise on participation, version 2.4 and date 24/09/2015"))
        ConsentForm.add(new DataEnum("R8(CF)	","R8 Nominated representatives, relatives or friends of a (deceased) adult (versioned for rare disease only) version 2.1 and date 24/09/2015"))

        ParticipantType = new ArrayList()
        ParticipantType.add(new DataEnum("Proband","Proband"))
        ParticipantType.add(new DataEnum("Relative","Relative"))

        Consanguinity = new ArrayList()
        Consanguinity.add(new DataEnum("U","Unknown"))
        Consanguinity.add(new DataEnum("P","Possible"))
        Consanguinity.add(new DataEnum("N","No"))
        Consanguinity.add(new DataEnum("Y","Yes"))

        BiologicalRelationship = new ArrayList()
        BiologicalRelationship.add(new DataEnum("Mother","Mother"))
        BiologicalRelationship.add(new DataEnum("Father","Father"))
        BiologicalRelationship.add(new DataEnum("TwinsMonozygous","Twins-Monozygous"))
        BiologicalRelationship.add(new DataEnum("TwinsDizygous","Twins-Dizygous"))
        BiologicalRelationship.add(new DataEnum("TwinsUnknown","Twins-Unknown"))
        BiologicalRelationship.add(new DataEnum("FullSibling","FullSibling"))
        BiologicalRelationship.add(new DataEnum("FullSiblingM","Half Sibling (shared mother)"))
        BiologicalRelationship.add(new DataEnum("FullSiblingF","Half Sibling (shared father)"))
        BiologicalRelationship.add(new DataEnum("MaternalAunt","Maternal Aunt"))
        BiologicalRelationship.add(new DataEnum("PaternalAunt","Paternal Aunt"))
        BiologicalRelationship.add(new DataEnum("MaternalUncle","Maternal Uncle"))
        BiologicalRelationship.add(new DataEnum("PaternalUncle","Paternal Uncle"))
        BiologicalRelationship.add(new DataEnum("MaternalCousinSister","Maternal Cousin - child of mother's sister"))
        BiologicalRelationship.add(new DataEnum("MaternalCousinBrother","Maternal Cousin - child of mother's brother"))
        BiologicalRelationship.add(new DataEnum("PaternalCousinSister","Paternal Cousin - child of father's sister"))
        BiologicalRelationship.add(new DataEnum("PaternalCousinBrother","Paternal Cousin - child of father's brother"))
        BiologicalRelationship.add(new DataEnum("MaternalGrandmother","Maternal Grandmother"))
        BiologicalRelationship.add(new DataEnum("MaternalGrandfather","Maternal Grandfather"))
        BiologicalRelationship.add(new DataEnum("PaternalGrandmother","Paternal Grandmother"))
        BiologicalRelationship.add(new DataEnum("PaternalGrandfather","Paternal Grandfather"))
        BiologicalRelationship.add(new DataEnum("DoubleFirstCousin","Double First Cousin"))
        BiologicalRelationship.add(new DataEnum("FirstCousinOnceRemoved","First Cousin OnceRemoved"))
        BiologicalRelationship.add(new DataEnum("SecondCousin","Second Cousin"))
        BiologicalRelationship.add(new DataEnum("SecondCousinOnceRemoved","Second Cousin Once Removed"))
        BiologicalRelationship.add(new DataEnum("Son","Son"))
        BiologicalRelationship.add(new DataEnum("Daughter","Daughter"))
        BiologicalRelationship.add(new DataEnum("Other","Other (Please specify)"))

        GroupType = new ArrayList()
        GroupType.add(new DataEnum("1","Trio with Mother AND Father"))
        GroupType.add(new DataEnum("2","Trio with Mother OR Father AND other biological relative"))
        GroupType.add(new DataEnum("3","Trio with other biological relatives"))
        GroupType.add(new DataEnum("4","Duo with Mother OR Father"))
        GroupType.add(new DataEnum("5","Duo with other biological relative"))
        GroupType.add(new DataEnum("6","Families with more than 3 participants"))
        GroupType.add(new DataEnum("7","Singleton"))
        GroupType.add(new DataEnum("NOT_PROVIDED","Migration data value unknown"))

        SpecificDisease = new ArrayList()
        SpecificDisease.add(new DataEnum("10960"," Kabuki syndrome" ))
        SpecificDisease.add(new DataEnum("10964"," VACTERL-like phenotypes"))
        SpecificDisease.add(new DataEnum("11006","  Craniosynostosis syndromes"))
        SpecificDisease.add(new DataEnum("11021","  Familial Thoracic Aortic Aneurysm Disease"))
        SpecificDisease.add(new DataEnum("11022","  Brugada syndrome"))
        SpecificDisease.add(new DataEnum("11023","  Long QT syndrome"))
        SpecificDisease.add(new DataEnum("11024","  Catecholaminergic Polymorphic Ventricular Tachycardia"))
        SpecificDisease.add(new DataEnum("11025","  Arrhythmogenic Right Ventricular Cardiomyopathy"))
        SpecificDisease.add(new DataEnum("11027","  Dilated Cardiomyopathy and conduction defects"))
        SpecificDisease.add(new DataEnum("11028","  Hypertrophic Cardiomyopathy"))
        SpecificDisease.add(new DataEnum("11037","  Erythropoietic protoporphyria -  mild variant"))
        SpecificDisease.add(new DataEnum("11039","  Noonan syndrome"))
        SpecificDisease.add(new DataEnum("11040","  Noonan syndrome plus other features"))
        SpecificDisease.add(new DataEnum("11041","  Cardio-facio-cutaneous syndrome"))
        SpecificDisease.add(new DataEnum("11042","  LEOPARD syndrome"))
        SpecificDisease.add(new DataEnum("11043","  Costello syndrome"))
        SpecificDisease.add(new DataEnum("11044","  Legius syndrome"))
        SpecificDisease.add(new DataEnum("11045","  Balanced translocations with an unusual phenotype"))
        SpecificDisease.add(new DataEnum("11046","  Bardet-Biedl Syndrome"))
        SpecificDisease.add(new DataEnum("11047","  Primary ciliary dyskinesia"))
        SpecificDisease.add(new DataEnum("11048","  Non-CF bronchiectasis"))
        SpecificDisease.add(new DataEnum("11050","  Non-Fanconi anaemia"))
        SpecificDisease.add(new DataEnum("11051","  Vici Syndrome and other autophagy disorders"))
        SpecificDisease.add(new DataEnum("11053","  Congenital adrenal hypoplasia"))
        SpecificDisease.add(new DataEnum("11054","  Familial or syndromic hypoparathyroidism"))
        SpecificDisease.add(new DataEnum("11057","  IUGR and IGF abnormalities"))
        SpecificDisease.add(new DataEnum("11060","  Significant early-onset obesity with or without other endocrine features and short stature"))
        SpecificDisease.add(new DataEnum("11063","  Classical Beckwith-Wiedemann syndrome"))
        SpecificDisease.add(new DataEnum("11064","  Atypical Beckwith-Wiedemann syndrome"))
        SpecificDisease.add(new DataEnum("11065","  Simpson-Golabi-Behmel syndrome"))
        SpecificDisease.add(new DataEnum("11066","  Sotos syndrome"))
        SpecificDisease.add(new DataEnum("11067","  Weaver syndrome"))
        SpecificDisease.add(new DataEnum("11075","  Congenital anaemias"))
        SpecificDisease.add(new DataEnum("11076","  Congenital hearing impairment"))
        SpecificDisease.add(new DataEnum("11077","  Bilateral microtia"))
        SpecificDisease.add(new DataEnum("11078","  Choanal atresia"))
        SpecificDisease.add(new DataEnum("11079","  Hyperammonaemia"))
        SpecificDisease.add(new DataEnum("11080","  Ketotic hypoglycaemia"))
        SpecificDisease.add(new DataEnum("11081", "Lactic acidosis"))
        SpecificDisease.add(new DataEnum("11083"," Cerebral folate deficiency"))
        SpecificDisease.add(new DataEnum("11084"," Mucopolysaccharideosis -  Gaucher -  Fabry"))
        SpecificDisease.add(new DataEnum("11085"," Mitochondrial disorders"))
        SpecificDisease.add(new DataEnum("11086"," Peroxisomal biogenesis disorders"))
        SpecificDisease.add(new DataEnum("11087","Hereditary ataxia"))
        SpecificDisease.add(new DataEnum("11088"," Early onset dystonia"))
        SpecificDisease.add(new DataEnum("11089"," Hereditary spastic paraplegia"))
        SpecificDisease.add(new DataEnum("11091"," Genetic Epilepsies with Febrile Seizures Plus"))
        SpecificDisease.add(new DataEnum("11092","Familial Genetic Generalised Epilepsies"))
        SpecificDisease.add(new DataEnum("11093"," Familial Focal Epilepsies"))
        SpecificDisease.add(new DataEnum("11094"," Epileptic encephalopathy"))
        SpecificDisease.add(new DataEnum("11099"," Paediatric motor neuronopathies"))
        SpecificDisease.add(new DataEnum("11100"," Early onset and familial Parkinson's Disease"))
        SpecificDisease.add(new DataEnum("11101", "Classical tuberous sclerosis"))
        SpecificDisease.add(new DataEnum("11102", "Intellectual disability"))
        SpecificDisease.add(new DataEnum("11103", "Congenital myopathy"))
        SpecificDisease.add(new DataEnum("11104"," Distal myopathies"))


    }




}
